Fix categories in the NepomukBackup desktop file
Fixes this error (desktop-file-validate) -

error: (will be fatal in the future): value "Archiving" in key
"Categories" in group "Desktop Entry" requires another category to be
present among the following categories: Utility